name: Java CI with Gradle

on:
  push:
    branches: [ "aa2425" ]
  pull_request:
    branches: [ "aa2425" ]

permissions:
  contents: read
  checks: write
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'always'
      - name: Build with Gradle
        run: ./gradlew --refresh-dependencies build --scan
      - name: Summarize tests results
        uses: jeantessier/test-summary-action@v1
        if: always()
      - name: Jubbiot Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Jubbiot Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit   
